name: "Build"
on:
  pull_request: #TODO: Change to push
    branches:
      - master

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: v1-npm-deps-${{ hashFiles('**/package-lock.json') }}
          restore-keys: v1-npm-deps-

      - name: Install NPM modules
        run: npm ci

      - name: Run gulp build
        run: npm run build

      - name: Package with web-ext
        run: npm run package

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: TempoFlex.zip
          path: ./package/*.zip